name: Build Executable

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        include:
          - rid: linux-x64
            os: ubuntu-latest
          - rid: win-x64
            os: windows-latest
          - rid: osx-arm64
            os: macos-latest
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.rid }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Publish
        run: >
          dotnet publish src/DCLPulse/DCLPulse.csproj
          -c Release
          -r ${{ matrix.rid }}
          --self-contained
          -p:PublishSingleFile=true
          -p:GenerateProto=false
          -o ./artifacts/${{ matrix.rid }}

      - uses: actions/upload-artifact@v4
        with:
          name: dcl-pulse-${{ matrix.rid }}
          path: ./artifacts/${{ matrix.rid }}
