name: Publish 'latest' image

on:
  release:
    types:
      - "created"

jobs:
  cd-dcl-pulse:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-release.yml@main
    with:
      service-name: dcl-pulse
      dockerfile-url: https://raw.githubusercontent.com/decentraland/Pulse/main/src/DCLPulse/Dockerfile
      deployment-environment: prd
    secrets: inherit
