name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  cd-dcl-pulse:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@main
    with:
      service-name: pulse-server
      dockerfile-url: https://raw.githubusercontent.com/decentraland/Pulse/main/src/DCLPulse/Dockerfile
      deployment-environment: dev
    secrets: inherit
